# This workflow will build a Java project with Maven
# For more information see: https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven

name: build

on:
  push:
    paths:
      - "pom.xml"
      - "src/main/java/me/grison/redux4j/*.java"
      - "src/test/java/me/grison/**/*.java"
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Codecov
        uses: codecov/codecov-action@v1.3.2
        with:
          file: ./target/site/jacoco/jacoco.xml