# This workflow will build a Java project with Maven
# For more information see: https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven

name: release

on:
  push:
    paths:
      - "pom.xml"
      - "src/main/java/me/grison/redux4j/*.java"
      - "src/test/java/me/grison/**/*.java"
    branches: [ 'releases/**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Codecov
        uses: codecov/codecov-action@v1.3.2
        with:
          file: ./target/site/jacoco/jacoco.xml
      - name: Receiving GPG key
        run: gpg --keyserver hkp://hkps.pool.sks-keyservers.net --recv-keys ${{secrets.GPG_KEYID}}
      - name: Import GPG Owner Trust
        run: echo ${{secrets.GPG_OWNERTRUST}} | base64 --decode | gpg --import-ownertrust
      - name: Import GPG key
        run: echo ${{secrets.GPG_SECRET_KEYS}} | base64 --decode | gpg --import --no-tty --batch --yes
      - name: Clean settings.xml
        run: sudo rm -rf ~/.m2/settings.xml
      - name: Create settings.xml
        uses: s4u/maven-settings-action@v1
        with:
          servers: '[{"id": "ossrh", "username": "${{secrets.SONATYPE_USERNAME}}", "password": "${{secrets.SONATYPE_PASSWORD}}"}]'
      - name: Deploy a new version to central
        run: mvn clean deploy -B -DskipTests -DskipExamples -Prelease -Dgpg.keyname=${{secrets.GPG_KEYNAME}} -Dgpg.passphrase=${{secrets.GPG_PASSPHRASE}}




